version: '3.8'
services:
  requestDocker:
    profiles: [ "docker" ]
    container_name: requestDocker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_EUREKA_URL=eurekaDocker
    image: kevinsantiagorey/unir_requests:v.0.1
    ports:
      - "8081:8081"
    networks:
      - eureka_unirEureka
    depends_on:
      - db
      - pgadmin


  db:
    profiles: [ "db", "docker" ]
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: requests
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - eureka_unirEureka

  pgadmin:
    profiles: [ "db", "docker" ]
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - eureka_unirEureka
    restart: unless-stopped
    depends_on:
      - db


networks:
  eureka_unirEureka:
    external: true