eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9191

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://BOOKS
          predicates:
            - Path=/api/v1/books/**
        - id: ORDER-SERVICE
          uri: lb://REQUESTS
          predicates:
            - Path=/api/v1/requests/**


